### PR TITLE
[utils] Rename postUpdateCheckFirst and sendCommandCheckFirst

### LINKED ISSUE #185: [utils] Rename postUpdateCheckFirst and sendCommandCheckFirst
`utils.py` functions `postUpdateCheckFirst` and `sendCommandCheckFirst` do not have names particularly evident of their function. I suggest renaming them to `postUpdateIfDifferent` and `sendCommandIfDifferent` for clarity, and creating aliases for the old names to maintain backwards compatibility.

### PR DESCRIPTION
**Pull request by CrazyIvan359**
Updates names of `postUpdateCheckFirst` and `sendCommandCheckFirst` to `postUpdateIfDifferent` and `sendCommandIfDifferent`. The old names are not very clear about the use of the function. The original names have been preserved as aliases for backwards compatibility.

Fixes #185 

Signed-off-by: Mike Murton <6764025+CrazyIvan359@users.noreply.github.com>

### CODE REVIEW

**Comment by openhab-5iver** [comment]
I almost merged, but had a thought. What if we used this as an opportunity to snake_case them?

**Comment by CrazyIvan359** [comment]
Didn't we decide we should be going the other way? The goal is to merge most of these libraries into oh core or an addon, oh is all camelCase.

**Comment by openhab-5iver** [comment]
> Didn't we decide we should be going the other way? 

No... if anything, everything should be converted to snake_case to help prevent name conflicts.

**Comment by CrazyIvan359** [comment]
While I agree with that, wouldn't that be bizarre after integration with oh? Having oh in camelCase and our addon in snake_case.

**Comment by openhab-5iver** [comment]
Why do you think it would be bizarre? Once the Scripting API is in place, everything will be in mixedCase, except for anything still left in the libraries. I think it would help to differentiate what you are using.

**Comment by CrazyIvan359** [comment]
Oh I see, you don't mean to avoid naming conflicts with OH as it is now, you mean between the HLs as they are now and the forthcoming API!

**Comment by openhab-5iver** [comment]
Correct. There could potentially be other things in OH or Java too, but the Scripting API would be a major source of name conflicts.

**Comment by CrazyIvan359** [comment]
Yes, now I understand. I will update the names

**Comment by besynnerlig** [comment]
Even though the original names have been preserved as aliases for backwards compatibility, maybe we should consider to rework all the included libraries and examples (e.g. only ideAlarm a.f.a.i.k) to use the new names.

**Comment by openhab-5iver** [comment]
Once this is merged, I'll update any usage in the repo with new function names...

https://github.com/openhab-scripters/openhab-helper-libraries/search?q=postupdatecheckfirst&unscoped_q=postupdatecheckfirst
https://github.com/openhab-scripters/openhab-helper-libraries/search?q=sendcommandcheckfirst&unscoped_q=sendcommandcheckfirst

**Comment by CrazyIvan359** [comment]
@openhab-5iver shouldn't that renaming happen in this PR?

**Comment by openhab-5iver** [comment]
Yes, but I didn't want to make work for you. But you're going to need to rebase anyhow, so might as well get it in.

**Comment by CrazyIvan359** [comment]
Rebase seems like a lot of trouble for a small PR like this. Just make the changes to master and close this PR with a reference to the commit instead.

**Pull request closed without merging**
