### PR TITLE
UpdateActions.rst to reflect 2.x mail binding action

### PR DESCRIPTION
**Pull request by vzorglub**
UpdateActions.str to reflect new mail binding action
Signed-off-by: Vincent Regaud <vzorglub@gmail.com>

### CODE REVIEW

**Comment by openhab-5iver** [comment]
This gets frustrating... but you're learning something new! You added the sign-off into the body of the PR but not into the commit message, which gets stored with the commit and is used to identify the commiter. :slightly_frowning_face:

Let me know before you run off in frustration, because I can do some magic behind the scenes. I'd rather not though, since it is a good learning experience.

**Comment by vzorglub** [comment]
Do it,
I think GitHub is great but I cannot get my head around how it works
I have tried before and it’s just a maze of unnecessary complications

And don’t get me started on trying to use it locally... That is black magic
I just don’t get it

**Comment by vzorglub** [comment]
You added the sign-off into the body of the PR but not into the commit message, which gets stored with the commit and is used to identify the commiter.

Next time hopefully

**Comment by rkoshak** [comment]
> And don’t get me started on trying to use it locally... That is black magic
I just don’t get it

I've actually found that working through VSCode is more self explanatory and intuitive. I wrote up a reply to a thread on the forum somewhere...

https://community.openhab.org/t/dco-check-signing-off-with-github-web-editor-explanation/83330/6

Maybe this will make the workflow a little easier on you. I know it has for me.

**Pull request merged**
