### PR TITLE
Initial migration of Javascript libraries

### LINKED ISSUE #120: Add Javascript libraries
Continuation of https://github.com/lewie/openhab2-javascript/issues/4 now that #94 is complete

@lewie, how would you like to proceed? Would you like me to get things copied over first, using the new directory structure, or would you prefer to do that yourself? I've already added startup delay scripts, and I have a JS OSGI library to add too.

### PR DESCRIPTION
**Pull request by openhab-5iver**
Resolves #120.

**Changes made to original JS libraries:**

1. Corrected paths for the new directory structure
2. Changed helper.mainPath to `automationPath + 'lib/javascript/core/'`
3. Changed the default logger to `jsr223.javascript` (I'd like to remove the jsr223, for Jython too, so this may be a good time to do it)
4. Moved the README.md to Docs/Javascript/
5. Renamed JSRule.js to rules.js
6. Renamed helper.js to utils.js
7. Split triggersAndConditions.js into triggers.js and conditions.js
8. Renamed a couple example scripts
9. Commented out imports in utils.js (helper.js) that are included in 'default' preset
9. Misc cleanup

If you have helper libraries for more than one language, there will be more than one startup delay script. This may not be optimal, but doesn't hurt anything. 

Signed-off-by: Scott Rushworth <openhab@5iver.com>

### CODE REVIEW

**Comment by Confectrician** [comment]
I would suggest to add issues for your listed suggestion points above.

We can than talk about or implemnt them in pieces.

**Comment by lewie** [comment]
@openhab-5iver,
if you want, you can still use this formatting for the header:
```
@author Helmut Lehmeyer <helmut.lehmeyer@gmail.com> - initial contribution.
```
**In "Changes made to original JS libraries:"**
All other points are perfect.

**In "Suggestions":**
Unify what seems to you to make sense full! We want as much agreement as possible between the languages.
to 3) No "ON/OFF" is not added as things! This was an older Version I think, where I mapped the OnOffType class.

**Comment by openhab-5iver** [comment]
@lewie, I'd sent you an invite to the maintains team, but I see you have not accepted it yet. It would be nice if you cod do a review/approval, but that wouldn't be possible until that is done. I'll go ahead an merge this, and we can clean things up in PRs. I did not include the email address in the header, since there would be cleanup needed if/when the address changed and we can be contacted through GH or the forum. If this is an issue for you, we can change it later or discuss in #131.

**Comment by lewie** [comment]
@openhab-5iver,
great, thanks! The e-mail in the header also has disadvantages, let's omit it.

**Pull request merged**
