### PR TITLE
Docker doc update

### PR DESCRIPTION
**Pull request by BifbofII**
Small fixes to the documentation that I noticed while trying to add Jython support to a Docker install.

### CODE REVIEW

**Comment by BifbofII** [comment]
I signed the commits. Anything else missing?

**Comment by openhab-5iver** [comment]
Looks like you got the Signed-off-by (thank you!), but there is another piece to it... https://help.github.com/en/github/authenticating-to-github/about-commit-signature-verification.

**Comment by BifbofII** [comment]
Sorry about the iterations, I hadn't worked with signed commits yet.

**Comment by openhab-5iver** [comment]
Thank you!

**Pull request merged**
